# Generated by Django 3.2 on 2021-05-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='img/default.jpg', upload_to='profile_pics/'),
        ),
    ]
